# Generated by Django 3.2 on 2022-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('pdf', models.FileField(upload_to='media/files/pdfs/')),
            ],
        ),
    ]
