# Generated by Django 3.2 on 2022-07-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("useraccount", "0002_reviewrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
