# Generated by Django 3.2 on 2022-07-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spotters',
            field=models.DecimalField(decimal_places=2, default=150, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(choices=[('Drone Survey with Photos', 'Drone Survey with Photos'), ('Drone Survey with Video & Photos', 'Drone Survey with Video & Photos'), ('Drone Survey with Videos & Photos with Thermal Images', 'Drone Survey with Videos & Photos with Thermal Images'), ('Drone Survey Edited Video & Recommendations of Works Required', 'Drone Survey Edited Video & Recommendations of Works Required'), ('Drone Survey with Surveyor Report', 'Drone Survey with Surveyor Report')], default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='spotters',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=6),
        ),
    ]
