# Generated by Django 3.2 on 2022-07-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
        ('payment', '0007_auto_20220704_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='useraccount.useraccount'),
        ),
    ]
