# Generated by Django 3.2 on 2022-08-23 10:31

from django.db import migrations, models
import io


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='actioned',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default=io.open, max_length=50),
        ),
    ]
