# Generated by Django 3.2 on 2022-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='includes',
            field=models.CharField(choices=[('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area            & Photos', 'Pre-site Survey & Risk Assessment,             Drone Survey of Intended Area & Photos'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area,            Videos & Photos', 'Pre-site Survey & Risk Assessment,            Drone Survey of Intended Area, Videos & Photos'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area,            Videos, Photos & Thermal Imaging', 'Pre-site Survey & Risk                Assessment, Drone Survey of Intended Area,                Videos, Photos & Thermal Imaging'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area,            Edited Video Presentation & Recommendations of Works Required', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area,            Edited Video Presentation & Recommendations of Works Required'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area             & Surveyor Report', 'Pre-site Survey & Risk Assessment,                Drone Survey of Intended Area & Surveyor Report')], max_length=254),
        ),
    ]
