# Generated by Django 3.2 on 2022-06-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='services',
            new_name='name',
        ),
    ]
