# Generated by Django 3.2 on 2022-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
    ]
