# Generated by Django 3.2 on 2022-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(choices=[('Drone Survey with Photos', 'Drone Survey with Photos'), ('Drone Survey with Video & Photos', 'Drone Survey with Video & Photos'), ('Drone Survey with Videos & Photos with Thermal Images', 'Drone Survey with Videos & Photos with Thermal Images'), ('Drone Survey Edited Video & Recommendations of Works Required', 'Drone Survey Edited Video & Recommendations of Works Required'), ('Drone Survey with Surveyor Report', 'Drone Survey with Surveyor Report')], max_length=254),
        ),
        migrations.AlterField(
            model_name='service',
            name='includes',
            field=models.CharField(choices=[('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area & Photos', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area & Photos'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Videos & Photos', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Videos & Photos'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Videos, Photos & Thermal Imaging', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Videos, Photos & Thermal Imaging'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Editied Video Presentation & Recommendations of Works Required', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area, Editied Video Presentation & Recommendations of Works Required'), ('Pre-site Survey & Risk Assessment, Drone Survey of Intended Area & Surveyor Report', 'Pre-site Survey & Risk Assessment, Drone Survey of Intended Area & Surveyor Report')], max_length=254),
        ),
    ]
