# Generated by Django 3.2 on 2022-06-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_services_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='includes',
            field=models.CharField(choices=[('Drone survey with photos', 'Drone survey with photos'), ('Drone survey with Video & photos', 'Drone survey with Video & photos'), ('Drone survey with videos & photos with thermal images', 'Drone survey with videos & photos with thermal images'), ('Drone survey edited version & recommendations of work', 'Drone survey edited version & recommendations of work'), ('Drone survey with surveyor report', 'Drone survey with surveyor report')], max_length=100),
        ),
    ]
