# Generated by Django 3.2 on 2022-06-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_price',
        ),
    ]
