# Generated by Django 3.2 on 2022-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220615_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='grande_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
