# Generated by Django 3.2 on 2022-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_grande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, default='pending.png', upload_to=''),
        ),
    ]
