# Generated by Django 3.2 on 2022-06-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='media',
            field=models.FileField(blank=True, default='noimage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, default='noimage.png', upload_to=''),
        ),
    ]
