# Generated by Django 3.2 on 2022-06-16 17:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20220616_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='media',
        ),
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, default='noimage.png'),
        ),
    ]
