# Generated by Django 3.2 on 2022-06-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20220616_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='video_url',
        ),
    ]
