# Generated by Django 3.2 on 2022-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Completed', 'Completed')], default='Started', max_length=10),
        ),
    ]
