# Generated by Django 3.2 on 2022-06-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20220622_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='grande_total',
            new_name='grand_total',
        ),
    ]
